import { useState, useRef } from "react";
import { Header } from "@/components/Header";
import { CyberCard } from "@/components/ui/cyber-card";
import { CyberButton } from "@/components/ui/cyber-button";
import { LoadingScanner } from "@/components/LoadingScanner";
import { ResultDisplay } from "@/components/ResultDisplay";
import { Textarea } from "@/components/ui/textarea";
import { Upload, Search, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { useLanguage } from "@/contexts/LanguageContext";

interface SourceInfo {
  name: string;
  url: string;
  type: "fact-check" | "news" | "database" | "web" | "official";
  contribution: number;
}

interface AnalysisResult {
  isReal: boolean;
  confidence: number;
  reason: string;
  reasonPoints?: string[];
  sources?: SourceInfo[];
  verdict?: "REAL" | "FAKE" | "MISLEADING" | "UNVERIFIED";
}

const ImageDetection = () => {
  const [image, setImage] = useState<string | null>(null);
  const [context, setContext] = useState("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { language, t } = useLanguage();

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        toast.error(language === "en" ? "Image must be less than 5MB" : "చిత్రం 5MB కంటే తక్కువగా ఉండాలి");
        return;
      }

      const reader = new FileReader();
      reader.onload = (event) => {
        setImage(event.target?.result as string);
        setResult(null);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleAnalyze = async () => {
    if (!image) {
      toast.error(language === "en" ? "Please upload an image to analyze" : "దయచేసి విశ్లేషించడానికి చిత్రాన్ని అప్‌లోడ్ చేయండి");
      return;
    }

    setIsAnalyzing(true);
    setResult(null);

    try {
      const { data, error } = await supabase.functions.invoke("analyze-content", {
        body: { 
          type: "image", 
          content: image,
          context: context || undefined,
          language
        },
      });

      if (error) {
        if (error.message?.includes("429")) {
          toast.error(language === "en" ? "Rate limit exceeded. Please try again later." : "రేట్ లిమిట్ మించిపోయింది.");
        } else if (error.message?.includes("402")) {
          toast.error(language === "en" ? "Usage limit reached. Please add credits to continue." : "వినియోగ పరిమితి చేరుకుంది.");
        } else {
          throw error;
        }
        return;
      }

      if (data.error) {
        toast.error(data.error);
        return;
      }

      setResult(data);
    } catch (error) {
      console.error("Analysis error:", error);
      toast.error(language === "en" ? "Failed to analyze image. Please try again." : "చిత్రాన్ని విశ్లేషించడం విఫలమైంది.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleDownloadReport = () => {
    if (!result) return;

    const sourcesText = result.sources 
      ? result.sources.map(s => `- ${s.name} (${s.type}): ${s.contribution}% - ${s.url}`).join("\n")
      : "AI Analysis";

    const reasonPointsText = result.reasonPoints 
      ? result.reasonPoints.map((p, i) => `${i + 1}. ${p}`).join("\n")
      : "";

    const report = `
TRUTHSCAN ANALYSIS REPORT
=========================
Date: ${new Date().toISOString()}
Type: Image Analysis
Verdict: ${result.verdict || (result.isReal ? "REAL" : "FAKE")}

CONTEXT PROVIDED:
${context || "No context provided"}

CONFIDENCE: ${result.confidence.toFixed(1)}%

ANALYSIS SUMMARY:
${result.reason}

DETAILED REASONING:
${reasonPointsText}

VERIFICATION SOURCES:
${sourcesText}

---
Generated by TruthScan AI Detection System
Powered by Dual AI (Gemini + OpenAI)
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `truthscan-image-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(language === "en" ? "Report downloaded successfully" : "నివేదిక విజయవంతంగా డౌన్‌లోడ్ అయింది");
  };

  const handleClear = () => {
    setImage(null);
    setContext("");
    setResult(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  return (
    <div className="min-h-screen bg-background cyber-grid">
      <div className="fixed inset-0 scanline pointer-events-none z-50 opacity-20" />
      
      <Header showBack />

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        <div className="text-center mb-8">
          <h1 className="font-display text-3xl font-bold text-neon-cyan text-glow-cyan tracking-wider mb-2">
            {t.imageDetection}
          </h1>
          <p className="text-muted-foreground font-mono">
            {t.uploadImage}
          </p>
        </div>

        <CyberCard variant="cyan" size="lg" className="mb-6">
          <div className="space-y-4">
            {/* Image Upload Area */}
            <div
              onClick={() => fileInputRef.current?.click()}
              className={cn(
                "relative border-2 border-dashed rounded-lg p-8 text-center cursor-pointer transition-all duration-300",
                "border-neon-cyan/30 hover:border-neon-cyan/60 hover:bg-neon-cyan/5",
                image && "border-neon-cyan/50 bg-neon-cyan/10"
              )}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleFileSelect}
                className="hidden"
                disabled={isAnalyzing}
              />

              {image ? (
                <div className="space-y-4">
                  <img
                    src={image}
                    alt="Uploaded"
                    className="max-h-64 mx-auto rounded-lg border border-neon-cyan/30"
                  />
                  <p className="text-neon-cyan font-mono text-sm">
                    {language === "en" ? "Click to change image" : "చిత్రాన్ని మార్చడానికి క్లిక్ చేయండి"}
                  </p>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="w-16 h-16 mx-auto rounded-full bg-neon-cyan/20 flex items-center justify-center">
                    <Upload className="w-8 h-8 text-neon-cyan" />
                  </div>
                  <div>
                    <p className="text-foreground font-mono">
                      {t.clickToUpload}
                    </p>
                    <p className="text-muted-foreground text-sm font-mono">
                      PNG, JPG, WEBP up to 5MB
                    </p>
                  </div>
                </div>
              )}
            </div>

            {/* Context Input */}
            <div className="space-y-2">
              <label className="block font-mono text-sm text-muted-foreground">
                {t.contextOptional}
              </label>
              <Textarea
                value={context}
                onChange={(e) => setContext(e.target.value)}
                placeholder={t.contextPlaceholder}
                className="bg-muted/50 border-border/50 font-mono resize-none focus:border-neon-cyan focus:ring-neon-cyan"
                rows={3}
                disabled={isAnalyzing}
              />
            </div>
            
            <div className="flex gap-4">
              <CyberButton
                variant="cyan"
                onClick={handleAnalyze}
                disabled={isAnalyzing || !image}
                className="flex-1"
              >
                <Search className="w-4 h-4" />
                {isAnalyzing ? t.analyzing : t.detectImage}
              </CyberButton>
              
              <CyberButton
                variant="outline"
                onClick={handleClear}
                disabled={isAnalyzing}
              >
                <Trash2 className="w-4 h-4" />
              </CyberButton>
            </div>
          </div>
        </CyberCard>

        {isAnalyzing && <LoadingScanner text={t.scanningImage} />}

        {result && !isAnalyzing && (
          <ResultDisplay
            isReal={result.isReal}
            confidence={result.confidence}
            reason={result.reason}
            reasonPoints={result.reasonPoints}
            sources={result.sources}
            verdict={result.verdict}
            onDownloadReport={handleDownloadReport}
            category="IMAGE"
          />
        )}
      </main>
    </div>
  );
};

export default ImageDetection;
