import { useState, useRef, useCallback } from "react";
import { Header } from "@/components/Header";
import { CyberCard } from "@/components/ui/cyber-card";
import { CyberButton } from "@/components/ui/cyber-button";
import { LoadingScanner } from "@/components/LoadingScanner";
import { ResultDisplay } from "@/components/ResultDisplay";
import { Camera, CameraOff, Search, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

interface AnalysisResult {
  isReal: boolean;
  confidence: number;
  reason: string;
}

const LiveScan = () => {
  const [capturedImage, setCapturedImage] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [isCameraActive, setIsCameraActive] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);

  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: "environment" },
      });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
      setIsCameraActive(true);
    } catch (error) {
      console.error("Camera error:", error);
      toast.error("Could not access camera. Please check permissions.");
    }
  };

  const stopCamera = useCallback(() => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((track) => track.stop());
      streamRef.current = null;
    }
    setIsCameraActive(false);
  }, []);

  const captureImage = () => {
    if (!videoRef.current) return;

    const canvas = document.createElement("canvas");
    canvas.width = videoRef.current.videoWidth;
    canvas.height = videoRef.current.videoHeight;
    const ctx = canvas.getContext("2d");
    if (ctx) {
      ctx.drawImage(videoRef.current, 0, 0);
      const imageData = canvas.toDataURL("image/jpeg");
      setCapturedImage(imageData);
      stopCamera();
      setResult(null);
    }
  };

  const handleAnalyze = async () => {
    if (!capturedImage) {
      toast.error("Please capture an image first");
      return;
    }

    setIsAnalyzing(true);
    setResult(null);

    try {
      const { data, error } = await supabase.functions.invoke("analyze-content", {
        body: { 
          type: "live", 
          content: capturedImage,
        },
      });

      if (error) {
        if (error.message?.includes("429")) {
          toast.error("Rate limit exceeded. Please try again later.");
        } else if (error.message?.includes("402")) {
          toast.error("Usage limit reached. Please add credits to continue.");
        } else {
          throw error;
        }
        return;
      }

      setResult(data);
    } catch (error) {
      console.error("Analysis error:", error);
      toast.error("Failed to analyze image. Please try again.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleDownloadReport = () => {
    if (!result) return;

    const report = `
TRUTHSCAN ANALYSIS REPORT
=========================
Date: ${new Date().toISOString()}
Type: Live Scan Analysis

CAPTURE METHOD: Camera

VERDICT: ${result.isReal ? "VERIFIED REAL" : "FAKE/MANIPULATED DETECTED"}
CONFIDENCE: ${result.confidence.toFixed(1)}%

ANALYSIS:
${result.reason}

---
Generated by TruthScan AI Detection System
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `truthscan-live-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded successfully");
  };

  const handleClear = () => {
    setCapturedImage(null);
    setResult(null);
    stopCamera();
  };

  return (
    <div className="min-h-screen bg-background cyber-grid">
      <div className="fixed inset-0 scanline pointer-events-none z-50 opacity-20" />
      
      <Header showBack />

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        <div className="text-center mb-8">
          <h1 className="font-display text-3xl font-bold text-neon-magenta text-glow-magenta tracking-wider mb-2">
            LIVE SCAN
          </h1>
          <p className="text-muted-foreground font-mono">
            Capture photos for real-time verification
          </p>
        </div>

        <CyberCard variant="magenta" size="lg" className="mb-6">
          <div className="space-y-4">
            {/* Camera/Image Display Area */}
            <div
              className={cn(
                "relative border-2 border-dashed rounded-lg overflow-hidden transition-all duration-300",
                "border-neon-magenta/30 bg-muted/20 aspect-video"
              )}
            >
              {isCameraActive && !capturedImage ? (
                <>
                  <video
                    ref={videoRef}
                    autoPlay
                    playsInline
                    className="w-full h-full object-cover"
                  />
                  {/* Scanning overlay */}
                  <div className="absolute inset-0 pointer-events-none">
                    <div className="absolute inset-4 border-2 border-neon-magenta/50 rounded-lg" />
                    <div
                      className="absolute left-4 right-4 h-0.5 bg-gradient-to-r from-transparent via-neon-magenta to-transparent animate-scan"
                    />
                    {/* Corner brackets */}
                    <div className="absolute top-4 left-4 w-8 h-8 border-t-2 border-l-2 border-neon-magenta" />
                    <div className="absolute top-4 right-4 w-8 h-8 border-t-2 border-r-2 border-neon-magenta" />
                    <div className="absolute bottom-4 left-4 w-8 h-8 border-b-2 border-l-2 border-neon-magenta" />
                    <div className="absolute bottom-4 right-4 w-8 h-8 border-b-2 border-r-2 border-neon-magenta" />
                  </div>
                </>
              ) : capturedImage ? (
                <img
                  src={capturedImage}
                  alt="Captured"
                  className="w-full h-full object-cover"
                />
              ) : (
                <div className="absolute inset-0 flex flex-col items-center justify-center text-center p-8">
                  <div className="w-16 h-16 rounded-full bg-neon-magenta/20 flex items-center justify-center mb-4">
                    <Camera className="w-8 h-8 text-neon-magenta" />
                  </div>
                  <p className="text-foreground font-mono mb-2">
                    Camera not active
                  </p>
                  <p className="text-muted-foreground text-sm font-mono">
                    Click "Start Camera" to begin scanning
                  </p>
                </div>
              )}
            </div>

            {/* Camera Controls */}
            <div className="flex gap-4 flex-wrap">
              {!capturedImage && (
                <>
                  {isCameraActive ? (
                    <>
                      <CyberButton
                        variant="secondary"
                        onClick={captureImage}
                        className="flex-1"
                      >
                        <Camera className="w-4 h-4" />
                        CAPTURE
                      </CyberButton>
                      <CyberButton
                        variant="outline"
                        onClick={stopCamera}
                      >
                        <CameraOff className="w-4 h-4" />
                      </CyberButton>
                    </>
                  ) : (
                    <CyberButton
                      variant="secondary"
                      onClick={startCamera}
                      className="flex-1"
                    >
                      <Camera className="w-4 h-4" />
                      START CAMERA
                    </CyberButton>
                  )}
                </>
              )}

              {capturedImage && (
                <>
                  <CyberButton
                    variant="secondary"
                    onClick={handleAnalyze}
                    disabled={isAnalyzing}
                    className="flex-1"
                  >
                    <Search className="w-4 h-4" />
                    {isAnalyzing ? "SCANNING..." : "SCAN IMAGE"}
                  </CyberButton>
                  <CyberButton
                    variant="outline"
                    onClick={handleClear}
                    disabled={isAnalyzing}
                  >
                    <Trash2 className="w-4 h-4" />
                  </CyberButton>
                </>
              )}
            </div>
          </div>
        </CyberCard>

        {isAnalyzing && <LoadingScanner text="PERFORMING LIVE SCAN ANALYSIS" />}

        {result && !isAnalyzing && (
          <ResultDisplay
            isReal={result.isReal}
            confidence={result.confidence}
            reason={result.reason}
            onDownloadReport={handleDownloadReport}
            category="LIVE SCAN"
          />
        )}
      </main>
    </div>
  );
};

export default LiveScan;
