import { useState } from "react";
import { Header } from "@/components/Header";
import { CyberCard } from "@/components/ui/cyber-card";
import { CyberButton } from "@/components/ui/cyber-button";
import { LoadingScanner } from "@/components/LoadingScanner";
import { ResultDisplay } from "@/components/ResultDisplay";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Search, Trash2, Twitter, Instagram, Facebook } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { useLanguage } from "@/contexts/LanguageContext";

interface SourceInfo {
  name: string;
  url: string;
  type: "fact-check" | "news" | "database" | "web" | "official";
  contribution: number;
}

interface AnalysisResult {
  isReal: boolean;
  confidence: number;
  reason: string;
  reasonPoints?: string[];
  sources?: SourceInfo[];
  verdict?: "REAL" | "FAKE" | "MISLEADING" | "UNVERIFIED";
}

const SocialMediaDetection = () => {
  const [content, setContent] = useState("");
  const [platform, setPlatform] = useState<string>("twitter");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const { language, t } = useLanguage();

  const handleAnalyze = async () => {
    if (!content.trim()) {
      toast.error(language === "en" ? "Please enter social media content to analyze" : "దయచేసి విశ్లేషించడానికి సోషల్ మీడియా కంటెంట్ నమోదు చేయండి");
      return;
    }

    setIsAnalyzing(true);
    setResult(null);

    try {
      const { data, error } = await supabase.functions.invoke("analyze-content", {
        body: { 
          type: "social", 
          content,
          platform,
          language
        },
      });

      if (error) {
        if (error.message?.includes("429")) {
          toast.error(language === "en" ? "Rate limit exceeded. Please try again later." : "రేట్ లిమిట్ మించిపోయింది.");
        } else if (error.message?.includes("402")) {
          toast.error(language === "en" ? "Usage limit reached. Please add credits to continue." : "వినియోగ పరిమితి చేరుకుంది.");
        } else {
          throw error;
        }
        return;
      }

      if (data.error) {
        toast.error(data.error);
        return;
      }

      setResult(data);
    } catch (error) {
      console.error("Analysis error:", error);
      toast.error(language === "en" ? "Failed to analyze content. Please try again." : "కంటెంట్‌ను విశ్లేషించడం విఫలమైంది.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleDownloadReport = () => {
    if (!result) return;

    const sourcesText = result.sources 
      ? result.sources.map(s => `- ${s.name} (${s.type}): ${s.contribution}% - ${s.url}`).join("\n")
      : "AI Analysis";

    const reasonPointsText = result.reasonPoints 
      ? result.reasonPoints.map((p, i) => `${i + 1}. ${p}`).join("\n")
      : "";

    const report = `
TRUTHSCAN ANALYSIS REPORT
=========================
Date: ${new Date().toISOString()}
Type: Social Media Troll Detection
Platform: ${platform.toUpperCase()}
Verdict: ${result.verdict || (result.isReal ? "GENUINE USER" : "TROLL/BOT DETECTED")}

CONTENT ANALYZED:
${content}

CONFIDENCE: ${result.confidence.toFixed(1)}%

ANALYSIS SUMMARY:
${result.reason}

DETAILED REASONING:
${reasonPointsText}

VERIFICATION SOURCES:
${sourcesText}

---
Generated by TruthScan AI Detection System
Powered by Dual AI (Gemini + OpenAI)
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `truthscan-social-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(language === "en" ? "Report downloaded successfully" : "నివేదిక విజయవంతంగా డౌన్‌లోడ్ అయింది");
  };

  const handleClear = () => {
    setContent("");
    setResult(null);
  };

  const getPlatformIcon = () => {
    switch (platform) {
      case "twitter":
        return <Twitter className="w-5 h-5" />;
      case "instagram":
        return <Instagram className="w-5 h-5" />;
      case "facebook":
        return <Facebook className="w-5 h-5" />;
      default:
        return <Twitter className="w-5 h-5" />;
    }
  };

  return (
    <div className="min-h-screen bg-background cyber-grid">
      <div className="fixed inset-0 scanline pointer-events-none z-50 opacity-20" />
      
      <Header showBack />

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        <div className="text-center mb-8">
          <h1 className="font-display text-3xl font-bold text-neon-red text-glow-red tracking-wider mb-2">
            {t.socialMediaTroll}
          </h1>
          <p className="text-muted-foreground font-mono">
            {t.detectTrolls}
          </p>
        </div>

        <CyberCard variant="red" size="lg" className="mb-6">
          <div className="space-y-4">
            {/* Platform Selection */}
            <div className="space-y-2">
              <label className="block font-mono text-sm text-muted-foreground">
                {t.selectPlatform}
              </label>
              <Select value={platform} onValueChange={setPlatform} disabled={isAnalyzing}>
                <SelectTrigger className="bg-muted/50 border-border/50 font-mono">
                  <div className="flex items-center gap-2">
                    {getPlatformIcon()}
                    <SelectValue placeholder="Select platform" />
                  </div>
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="twitter">
                    <div className="flex items-center gap-2">
                      <Twitter className="w-4 h-4" />
                      Twitter / X
                    </div>
                  </SelectItem>
                  <SelectItem value="instagram">
                    <div className="flex items-center gap-2">
                      <Instagram className="w-4 h-4" />
                      Instagram
                    </div>
                  </SelectItem>
                  <SelectItem value="facebook">
                    <div className="flex items-center gap-2">
                      <Facebook className="w-4 h-4" />
                      Facebook
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Content Input */}
            <div className="space-y-2">
              <label className="block font-mono text-sm text-muted-foreground">
                {t.pastePostContent}
              </label>
              <Textarea
                value={content}
                onChange={(e) => setContent(e.target.value)}
                placeholder={t.socialPlaceholder}
                className="min-h-[150px] bg-muted/50 border-border/50 font-mono resize-none focus:border-neon-red focus:ring-neon-red"
                disabled={isAnalyzing}
              />
            </div>
            
            <div className="flex gap-4">
              <CyberButton
                variant="destructive"
                onClick={handleAnalyze}
                disabled={isAnalyzing || !content.trim()}
                className="flex-1"
              >
                <Search className="w-4 h-4" />
                {isAnalyzing ? t.analyzing : t.detectTroll}
              </CyberButton>
              
              <CyberButton
                variant="outline"
                onClick={handleClear}
                disabled={isAnalyzing}
              >
                <Trash2 className="w-4 h-4" />
              </CyberButton>
            </div>
          </div>
        </CyberCard>

        {isAnalyzing && <LoadingScanner text={t.scanningTroll} />}

        {result && !isAnalyzing && (
          <ResultDisplay
            isReal={result.isReal}
            confidence={result.confidence}
            reason={result.reason}
            reasonPoints={result.reasonPoints}
            sources={result.sources}
            verdict={result.verdict}
            onDownloadReport={handleDownloadReport}
            category="SOCIAL MEDIA"
          />
        )}
      </main>
    </div>
  );
};

export default SocialMediaDetection;
