import { useState } from "react";
import { Header } from "@/components/Header";
import { CyberCard } from "@/components/ui/cyber-card";
import { CyberButton } from "@/components/ui/cyber-button";
import { LoadingScanner } from "@/components/LoadingScanner";
import { ResultDisplay } from "@/components/ResultDisplay";
import { Textarea } from "@/components/ui/textarea";
import { Search, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { useLanguage } from "@/contexts/LanguageContext";

interface SourceInfo {
  name: string;
  url: string;
  type: "fact-check" | "news" | "database" | "web" | "official";
  contribution: number;
}

interface AnalysisResult {
  isReal: boolean;
  confidence: number;
  reason: string;
  reasonPoints?: string[];
  sources?: SourceInfo[];
  verdict?: "REAL" | "FAKE" | "MISLEADING" | "UNVERIFIED";
}

const TextDetection = () => {
  const [text, setText] = useState("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const { language, t } = useLanguage();

  const handleAnalyze = async () => {
    if (!text.trim()) {
      toast.error(language === "en" ? "Please enter some text to analyze" : "దయచేసి విశ్లేషించడానికి కొంత టెక్స్ట్ నమోదు చేయండి");
      return;
    }

    setIsAnalyzing(true);
    setResult(null);

    try {
      const { data, error } = await supabase.functions.invoke("analyze-content", {
        body: { type: "text", content: text, language },
      });

      if (error) {
        // Supabase functions sometimes return error details inside error.context
        const specificError = (error as any).context?.error || (error as any).message;

        if (specificError?.includes("429")) {
          toast.error(language === "en" ? "Rate limit exceeded. Please try again later." : "రేట్ లిమిట్ మించిపోయింది. దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి.");
        } else if (specificError?.includes("402")) {
          toast.error(language === "en" ? "Usage limit reached. Please add credits to continue." : "వినియోగ పరిమితి చేరుకుంది.");
        } else if (specificError) {
          toast.error(specificError);
        } else {
          throw error;
        }
        return;
      }

      if (data.error) {
        toast.error(data.error);
        return;
      }

      setResult(data);
    } catch (error: any) {
      console.error("Analysis error:", error);
      const msg = error?.message || (language === "en" ? "Failed to analyze content. Please try again." : "కంటెంట్‌ను విశ్లేషించడం విఫలమైంది.");
      toast.error(msg);
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleDownloadReport = () => {
    if (!result) return;

    const sourcesText = result.sources 
      ? result.sources.map(s => `- ${s.name} (${s.type}): ${s.contribution}% - ${s.url}`).join("\n")
      : "AI Analysis";

    const reasonPointsText = result.reasonPoints 
      ? result.reasonPoints.map((p, i) => `${i + 1}. ${p}`).join("\n")
      : "";

    const report = `
TRUTHSCAN ANALYSIS REPORT
=========================
Date: ${new Date().toISOString()}
Type: Text Analysis
Verdict: ${result.verdict || (result.isReal ? "REAL" : "FAKE")}

CONTENT ANALYZED:
${text}

CONFIDENCE: ${result.confidence.toFixed(1)}%

ANALYSIS SUMMARY:
${result.reason}

DETAILED REASONING:
${reasonPointsText}

VERIFICATION SOURCES:
${sourcesText}

---
Generated by TruthScan AI Detection System
Powered by Dual AI (Gemini + OpenAI)
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `truthscan-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(language === "en" ? "Report downloaded successfully" : "నివేదిక విజయవంతంగా డౌన్‌లోడ్ అయింది");
  };

  const handleClear = () => {
    setText("");
    setResult(null);
  };

  return (
    <div className="min-h-screen bg-background cyber-grid">
      <div className="fixed inset-0 scanline pointer-events-none z-50 opacity-20" />
      
      <Header showBack />

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        <div className="text-center mb-8">
          <h1 className="font-display text-3xl font-bold text-primary text-glow-green tracking-wider mb-2">
            {t.textAnalysis}
          </h1>
          <p className="text-muted-foreground font-mono">
            {language === "en" ? "Paste any news article or text content to verify its authenticity" : "ప్రామాణికతను ధృవీకరించడానికి ఏదైనా వార్తా కథనం లేదా టెక్స్ట్ కంటెంట్‌ను పేస్ట్ చేయండి"}
          </p>
        </div>

        <CyberCard size="lg" className="mb-6">
          <div className="space-y-4">
            <label className="block font-mono text-sm text-muted-foreground">
              {t.enterTextToAnalyze}
            </label>
            <Textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder={t.textPlaceholder}
              className="min-h-[200px] bg-muted/50 border-border/50 font-mono resize-none focus:border-primary focus:ring-primary"
              disabled={isAnalyzing}
            />
            
            <div className="flex gap-4">
              <CyberButton
                onClick={handleAnalyze}
                disabled={isAnalyzing || !text.trim()}
                className="flex-1"
              >
                <Search className="w-4 h-4" />
                {isAnalyzing ? t.analyzing : t.checkNews}
              </CyberButton>
              
              <CyberButton
                variant="outline"
                onClick={handleClear}
                disabled={isAnalyzing}
              >
                <Trash2 className="w-4 h-4" />
              </CyberButton>
            </div>
          </div>
        </CyberCard>

        {isAnalyzing && <LoadingScanner text={language === "en" ? "SCANNING TEXT CONTENT" : "టెక్స్ట్ కంటెంట్‌ను స్కాన్ చేస్తోంది"} />}

        {result && !isAnalyzing && (
          <ResultDisplay
            isReal={result.isReal}
            confidence={result.confidence}
            reason={result.reason}
            reasonPoints={result.reasonPoints}
            sources={result.sources}
            verdict={result.verdict}
            onDownloadReport={handleDownloadReport}
            category="TEXT"
          />
        )}
      </main>
    </div>
  );
};

export default TextDetection;
