import { useState } from "react";
import { Header } from "@/components/Header";
import { CyberCard } from "@/components/ui/cyber-card";
import { CyberButton } from "@/components/ui/cyber-button";
import { LoadingScanner } from "@/components/LoadingScanner";
import { ResultDisplay } from "@/components/ResultDisplay";
import { Textarea } from "@/components/ui/textarea";
import { Search, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

interface AnalysisResult {
  isReal: boolean;
  confidence: number;
  reason: string;
}

const TextDetection = () => {
  const [text, setText] = useState("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);

  const handleAnalyze = async () => {
    if (!text.trim()) {
      toast.error("Please enter some text to analyze");
      return;
    }

    setIsAnalyzing(true);
    setResult(null);

    try {
      const { data, error } = await supabase.functions.invoke("analyze-content", {
        body: { type: "text", content: text },
      });

      if (error) {
        if (error.message?.includes("429")) {
          toast.error("Rate limit exceeded. Please try again later.");
        } else if (error.message?.includes("402")) {
          toast.error("Usage limit reached. Please add credits to continue.");
        } else {
          throw error;
        }
        return;
      }

      setResult(data);
    } catch (error) {
      console.error("Analysis error:", error);
      toast.error("Failed to analyze content. Please try again.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleDownloadReport = () => {
    if (!result) return;

    const report = `
TRUTHSCAN ANALYSIS REPORT
=========================
Date: ${new Date().toISOString()}
Type: Text Analysis

CONTENT ANALYZED:
${text}

VERDICT: ${result.isReal ? "VERIFIED REAL" : "FAKE DETECTED"}
CONFIDENCE: ${result.confidence.toFixed(1)}%

ANALYSIS:
${result.reason}

---
Generated by TruthScan AI Detection System
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `truthscan-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded successfully");
  };

  const handleClear = () => {
    setText("");
    setResult(null);
  };

  return (
    <div className="min-h-screen bg-background cyber-grid">
      <div className="fixed inset-0 scanline pointer-events-none z-50 opacity-20" />
      
      <Header showBack />

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        <div className="text-center mb-8">
          <h1 className="font-display text-3xl font-bold text-primary text-glow-green tracking-wider mb-2">
            TEXT ANALYSIS
          </h1>
          <p className="text-muted-foreground font-mono">
            Paste any news article or text content to verify its authenticity
          </p>
        </div>

        <CyberCard size="lg" className="mb-6">
          <div className="space-y-4">
            <label className="block font-mono text-sm text-muted-foreground">
              ENTER TEXT TO ANALYZE
            </label>
            <Textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Paste the news article, social media post, or any text content you want to verify..."
              className="min-h-[200px] bg-muted/50 border-border/50 font-mono resize-none focus:border-primary focus:ring-primary"
              disabled={isAnalyzing}
            />
            
            <div className="flex gap-4">
              <CyberButton
                onClick={handleAnalyze}
                disabled={isAnalyzing || !text.trim()}
                className="flex-1"
              >
                <Search className="w-4 h-4" />
                {isAnalyzing ? "ANALYZING..." : "CHECK NEWS"}
              </CyberButton>
              
              <CyberButton
                variant="outline"
                onClick={handleClear}
                disabled={isAnalyzing}
              >
                <Trash2 className="w-4 h-4" />
              </CyberButton>
            </div>
          </div>
        </CyberCard>

        {isAnalyzing && <LoadingScanner text="SCANNING TEXT CONTENT" />}

        {result && !isAnalyzing && (
          <ResultDisplay
            isReal={result.isReal}
            confidence={result.confidence}
            reason={result.reason}
            onDownloadReport={handleDownloadReport}
            category="TEXT"
          />
        )}
      </main>
    </div>
  );
};

export default TextDetection;
